name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Jalankan pipeline setiap ada push ke branch master
  pull_request:
    branches:
      - master  # Jalankan pipeline untuk setiap PR ke branch master

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 2: Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker-compose -f Docker-compose.yml build
    
    # Step 4: Push Docker image ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker-compose push

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # Step 3: Configure kubeconfig
    - name: Set kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > kubeconfig
        export KUBECONFIG=kubeconfig

    # Step 4: Apply Kubernetes manifests
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yml
