name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Jalankan pipeline setiap ada push ke branch master
  pull_request:
    branches:
      - master  # Jalankan pipeline untuk setiap PR ke branch master

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 2: Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker-compose -f Docker-compose.yml build
    
    # Step 4: Push Docker image ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker-compose -f Docker-compose.yml push 

  preparing-minikube:
    name: Install and start minikube
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Install minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/
          sudo apt-get install -y conntrack

      - name: Start minikube
        run: |
          minikube start --driver=docker

  setup-and-configuring-kubernetes:
    name: Setup and configuring Kubernetes
    needs: [build-and-push-docker, preparing-minikube]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Setup certificate
        run: |
          mkdir -p /tmp/kube
          echo "${{ secrets.MINIKUBEA_CRT _C}}" > /tmp/kube/ca.crt
          echo "${{ secrets.MINIKUBE_CLIENT_CRT }}" > /tmp/kube/client.crt
          echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" > /tmp/kube/client.key

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "apiVersion: v1 
          kind: Config
          preferences: {}
          clusters:
            - cluster:
                server: https://127.0.0.1:59282
                certificate-authority: /tmp/kube/ca.crt
              name: minikube
          context:
            - context:
                cluster: minikube
                user: minikube
                namespace: default
              name: minikube
          current-context: minikube
          users:
          - name: minikube
            user:
              client-certificate: /tmp/kube/client.crt
              client-key: /tmp/kube/client.key 
          " > ~/.kube/config

      - name: Set Kubernetes context
        run: |
          kubectl config set-context minikube \
            --cluster=minikube \
            --user=minikube \
            --namespace=default
          kubectl config use-context minikube