name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Jalankan pipeline setiap ada push ke branch master
  pull_request:
    branches:
      - master  # Jalankan pipeline untuk setiap PR ke branch master

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout kode dari repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Step 2: Login ke Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker image
    - name: Build Docker Image
      run: |
        docker-compose -f Docker-compose.yml build
    
    # Step 4: Push Docker image ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker-compose -f Docker-compose.yml push 

  deploy-to-kubernetes:
    name: Deploy to Kubernetes
    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          mkdir -p ~/.minikube
          echo "${{ secrets.MINIKUBE_CA_CRT }}" > ~/.minikube/ca.crt
          echo "${{ secrets.MINIKUBE_CLIENT_CRT }}" > ~/.minikube/client.crt
          echo "${{ secrets.MINIKUBE_CLIENT_KEY }}" > ~/.minikube/client.key
          echo "apiVersion: v1 
          kind: Config
          preferences: {}
          clusters:
            - cluster:
                server: https://127.0.0.1:59282
                certificate-authority: /.minikube/ca.crt
              name: minikube
          context:
            - context:
                cluster: minikube
                user: minikube
                namespace: default
              name: minikube
          current-context: minikube
          users:
          - name: minikube
            user:
              client-certificate: /.minikube/client.crt
              client-key: /.minikube/client.key 
          " > ~/.kube/config

      - name: Set Kubernetes context
        run: |
          kubectl config set-context minikube \
            --cluster=minikube \
            --user=minikube \
            --namespace=default
          kubectl config use-context minikube

      - name: Deploy to Kubernetes
        run: kubectl apply -f ./k8s/ --validate=false
